---
title: "Parental-Leave"
author: "Sophie Hensgen"
date: "7/3/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Packages, include=FALSE}

library(tidyverse)
library(dplyr)
library(foreign)
```




```{r Loading Data Sets, include=FALSE}

# $p (Mutterschutz variable, gender, employment, year of birth)
p96 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/mp.dta")
p97 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/np.dta")
p98 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/op.dta")
p99 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/pp.dta")
p00 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/qp.dta")
p01 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/rp.dta")
p02 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/sp.dta")
p03 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/tp.dta")
p04 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/up.dta")
p05 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/vp.dta")
p06 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/wp.dta")
p07 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/xp.dta")
p08 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/yp.dta")
p09 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/zp.dta")
p10 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bap.dta")
p11 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bbp.dta")
p12 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bcp.dta")
p13 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bdp.dta")
p14 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bep.dta")
p15 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bfp.dta")
p16 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bgp.dta")
p17 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bhp.dta")
p18 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bip.dta")
```


```{r Loading Data Sets, include=FALSE}

# $pequiv (gender, eductaion, occupation, region, annual working hours, income, age, longitudinal weights)
pequiv96 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/mpequiv.dta")
pequiv97 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/npequiv.dta")
pequiv98 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/opequiv.dta")
pequiv99 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/ppequiv.dta")
pequiv00 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/qpequiv.dta")
pequiv01 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/rpequiv.dta")
pequiv02 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/spequiv.dta")
pequiv03 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/tpequiv.dta")
pequiv04 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/upequiv.dta")
pequiv05 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/vpequiv.dta")
pequiv06 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/wpequiv.dta")
pequiv07 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/xpequiv.dta")
pequiv08 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/ypequiv.dta")
pequiv09 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/zpequiv.dta")
pequiv10 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bapequiv.dta")
pequiv11 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bbpequiv.dta")
pequiv12 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bcpequiv.dta")
pequiv13 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bdpequiv.dta")
pequiv14 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bepequiv.dta")
pequiv15 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bfpequiv.dta")
pequiv16 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bgpequiv.dta")
pequiv17 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bhpequiv.dta")
pequiv18 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bipequiv.dta")
```

```{r Loading Data Sets, include=FALSE}

# $pequiv (Number of Children in HH, Date of Birth (Child))
pkind96 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/mkind.dta")
pkind97 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/nkind.dta")
pkind98 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/okind.dta")
pkind99 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/pkind.dta")
pkind00 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/qkind.dta")
pkind01 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/rkind.dta")
pkind02 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/skind.dta")
pkind03 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/tkind.dta")
pkind04 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/ukind.dta")
pkind05 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/vkind.dta")
pkind06 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/wkind.dta")
pkind07 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/xkind.dta")
pkind08 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/ykind.dta")
pkind09 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/zkind.dta")
pkind10 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bakind.dta")
pkind11 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bbkind.dta")
pkind12 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bckind.dta")
pkind13 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bdkind.dta")
pkind14 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bekind.dta")
pkind15 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bfkind.dta")
pkind16 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bgkind.dta")
pkind17 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bhkind.dta")
pkind18 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bikind.dta")
```

```{r Loading Data Sets, include=FALSE}

# $pequiv (Year of Birth)
pp16 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bgp.dta")
pp17 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bhp.dta")
pp18 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bip.dta")
```

```{r Loading Data Sets, include=FALSE}

# $pequiv (Education, employment, hours of work, partner)
pgen96 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/mpgen.dta")
pgen97 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/npgen.dta")
pgen98 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/opgen.dta")
pgen99 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/ppgen.dta")
pgen00 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/qpgen.dta")
pgen01 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/rpgen.dta")
pgen02 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/spgen.dta")
pgen03 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/tpgen.dta")
pgen04 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/upgen.dta")
pgen05 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/vpgen.dta")
pgen06 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/wpgen.dta")
pgen07 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/xpgen.dta")
pgen08 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/ypgen.dta")
pgen09 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/zpgen.dta")
pgen10 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bapgen.dta")
pgen11 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bbpgen.dta")
pgen12 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bcpgen.dta")
pgen13 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bdpgen.dta")
pgen14 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bepgen.dta")
pgen15 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bfpgen.dta")
pgen16 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bgpgen.dta")
pgen17 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bhpgen.dta")
pgen18 <- read.dta("/Users/sophiehensgen/Webscraping-LS-Methode/Causal-Inferences-TP/cs-transfer/Stata/raw/bipgen.dta")
```


```{r look into data, include=FALSE}

head(p97)
head(pequiv97)
head(pkind97)
head(pgen97)
```


```{r join data frames (96), echo=FALSE}

all96 <- p96 %>% 
  full_join(pequiv96, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "mhhnr", "hid"), stringsAsFactors = FALSE)
all96 <- all96 %>%
  full_join(pkind96, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "mhhnr", "hid", "welle"), stringsAsFactors = FALSE)
all96 <- all96 %>%
  full_join(pgen96, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "mhhnr", "hid"), stringsAsFactors = FALSE)

```


```{r join data frames (96), echo=FALSE}

select96 <- all96 %>%
  select(persnr, pid, hhnr, cid, mp66f, d11102ll, d1110896, e1110196, l1110296, d1110796, mp10813, mp10502, isced97_96, partz96, lfs96, merwzeit, e1110196, i1111096, d1110196, w1110896) %>%
  rename(parleave = mp66f, sex = d11102ll, education = d1110896, occup = e1110196,  region = l1110296, kinderzahl =  d1110796, kindbd = mp10813, birthyear = mp10502, edisced = isced97_96, partner= partz96, employ = lfs96, workhpw = merwzeit, workhpy = e1110196, income = i1111096, age = d1110196, longweight = w1110896)

select96
```


```{r join data frames (97), include=FALSE}

all97 <- p97 %>% 
  full_join(pequiv97, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "nhhnr", "hid"), stringsAsFactors = FALSE)
all97 <- all97 %>%
  full_join(pkind97, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "nhhnr", "hid", "welle"), stringsAsFactors = FALSE)
all97 <- all97 %>%
  full_join(pgen97, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "nhhnr", "hid"), stringsAsFactors = FALSE)

all97

```


```{r join data frames (97), echo=FALSE}

select97 <- all97 %>%
  select(persnr, pid, hhnr, cid, np660f, d11102ll, d1110897, e1110197, l1110297, d1110797, np11513, np11202, isced97_97, partz97, lfs97, nerwzeit, e1110197, i1111097, d1110197, w1110897) %>%
  rename(parleave = np660f, sex = d11102ll, education = d1110897, occup = e1110197,  region = l1110297, kinderzahl = d1110797, kindbd = np11513, birthyear = np11202, edisced = isced97_97, partner= partz97, employ = lfs97, workhpw = nerwzeit, workhpy = e1110197, income = i1111097, age = d1110197, longweight = w1110897)

select97
```


```{r join data frames (98), include=FALSE}

all98 <- p98 %>% 
  full_join(pequiv98, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "ohhnr", "hid"), stringsAsFactors = FALSE)
all98 <- all98 %>%
  full_join(pkind98, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "ohhnr", "hid", "welle"), stringsAsFactors = FALSE)
all98 <- all98 %>%
  full_join(pgen98, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "ohhnr", "hid"), stringsAsFactors = FALSE)

all98

```


```{r join data frames (98), echo=FALSE}

select98 <- all98 %>%
  select(persnr, pid, hhnr, cid, op5706, d11102ll, d1110898, e1110198, l1110298, d1110798, op12113, op11802, isced97_98, partz98, lfs98, oerwzeit, e1110198, i1111098, d1110198, w1110898) %>%
  rename(parleave = op5706, sex = d11102ll, education = d1110898, occup = e1110198,  region = l1110298, kinderzahl = d1110798, kindbd = op12113, birthyear = op11802, edisced = isced97_98, partner= partz98, employ = lfs98, workhpw = oerwzeit, workhpy = e1110198, income = i1111098, age = d1110198, longweight = w1110898)

select98
```




```{r join data frames (99), include=FALSE}

all99 <- p99 %>% 
  full_join(pequiv99, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "phhnr", "hid"), stringsAsFactors = FALSE)
all99 <- all99 %>%
  full_join(pkind99, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "phhnr", "hid", "welle"), stringsAsFactors = FALSE)
all99 <- all99 %>%
  full_join(pgen99, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "phhnr", "hid"), stringsAsFactors = FALSE)

all99

```


```{r join data frames (99), echo=FALSE}

select99 <- all99 %>%
  select(persnr, pid, hhnr, cid, pp7506, d11102ll, d1110899, e1110199, l1110299, d1110799, pp13320, pp13002, isced97_99, partz99, lfs99, perwzeit, e1110199, i1111099, d1110199, w1110899) %>%
  rename(parleave = pp7506, sex = d11102ll, education = d1110899, occup = e1110199,  region = l1110299, kinderzahl = d1110799, kindbd = pp13320, birthyear = pp13002, edisced = isced97_99, partner= partz99, employ = lfs99, workhpw = perwzeit, workhpy = e1110199, income = i1111099, age = d1110199, longweight = w1110899)

select99
```

```{r join data frames (00), include=FALSE}

all00 <- p00 %>% 
  full_join(pequiv00, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "qhhnr", "hid"), stringsAsFactors = FALSE)
all00 <- all00 %>%
  full_join(pkind00, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "qhhnr", "hid", "welle"), stringsAsFactors = FALSE)
all00 <- all00 %>%
  full_join(pgen00, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "qhhnr", "hid"), stringsAsFactors = FALSE)

all00

```


```{r join data frames (00), echo=FALSE}

select00 <- all00%>%
  select(persnr, pid, hhnr, cid, qp7507, d11102ll, d1110800, e1110100, l1110200, d1110700, qp14220, qp13902, isced97_00, partz00, lfs00, qerwzeit, e1110100, i1111000, d1110100, w1110800) %>%
  rename(parleave = qp7507, sex = d11102ll, education = d1110800, occup = e1110100,  region = l1110200, kinderzahl = d1110700, kindbd = qp14220, birthyear = qp13902, edisced = isced97_00, partner= partz00, employ = lfs00, workhpw = qerwzeit, workhpy = e1110100, income = i1111000, age = d1110100, longweight = w1110800)

select00
select00$kindbd <- as.factor(select00$kindbd)
```

```{r join data frames (01), include=FALSE}

all01 <- p01 %>% 
  full_join(pequiv01, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "rhhnr", "hid"), stringsAsFactors = FALSE)
all01 <- all01 %>%
  full_join(pkind01, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "rhhnr", "hid", "welle"), stringsAsFactors = FALSE)
all01 <- all01 %>%
  full_join(pgen01, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "rhhnr", "hid"), stringsAsFactors = FALSE)

all01

```


```{r join data frames (01), echo=FALSE}

select01 <- all01 %>%
  select(persnr, pid, hhnr, cid, rp7507, d11102ll, d1110801, e1110101, l1110201, d1110701, rp13320, rp13002, isced97_01, partz01, lfs01, rerwzeit, e1110101, i1111001, d1110101, w1110801) %>%
  rename(parleave = rp7507, sex = d11102ll, education = d1110801, occup = e1110101,  region = l1110201, kinderzahl = d1110701, kindbd = rp13320, birthyear = rp13002, edisced = isced97_01, partner= partz01, employ = lfs01, workhpw = rerwzeit, workhpy = e1110101, income = i1111001, age = d1110101, longweight = w1110801)

select01
```

```{r join data frames (02), include=FALSE}

all02 <- p02 %>% 
  full_join(pequiv02, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "shhnr", "hid"), stringsAsFactors = FALSE)
all02 <- all02 %>%
  full_join(pkind02, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "shhnr", "hid", "welle"), stringsAsFactors = FALSE)
all02 <- all02 %>%
  full_join(pgen02, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "shhnr", "hid"), stringsAsFactors = FALSE)

all02

```


```{r join data frames (02), echo=FALSE}

select02 <- all02 %>%
  select(persnr, pid, hhnr, cid, sp7507, d11102ll, d1110802, e1110102, l1110202, d1110702, sp13320, sp13002, isced97_02, partz02, lfs02, serwzeit, e1110102, i1111002, d1110102, w1110802) %>%
  rename(parleave = sp7507, sex = d11102ll, education = d1110802, occup = e1110102,  region = l1110202, kinderzahl = d1110702, kindbd = sp13320, birthyear = sp13002, edisced = isced97_02, partner= partz02, employ = lfs02, workhpw = serwzeit, workhpy = e1110102, income = i1111002, age = d1110102, longweight = w1110802)

select02
```

```{r join data frames (03), include=FALSE}

all03 <- p03 %>% 
  full_join(pequiv03, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "thhnr", "hid"), stringsAsFactors = FALSE)
all03 <- all03 %>%
  full_join(pkind03, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "thhnr", "hid", "welle"), stringsAsFactors = FALSE)
all03 <- all03 %>%
  full_join(pgen03, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "thhnr", "hid"), stringsAsFactors = FALSE)

all03

```


```{r join data frames (03), echo=FALSE}

select03 <- all03 %>%
  select(persnr, pid, hhnr, cid, tp9307, d11102ll, d1110803, e1110103, l1110203, d1110703, tp14108, tp13602, isced97_03, partz03, lfs03, terwzeit, e1110103, i1111003, d1110103, w1110803) %>%
  rename(parleave = tp9307, sex = d11102ll, education = d1110803, occup = e1110103,  region = l1110203, kinderzahl = d1110703, kindbd = tp14108, birthyear = tp13602, edisced = isced97_03, partner= partz03, employ = lfs03, workhpw = terwzeit, workhpy = e1110103, income = i1111003, age = d1110103, longweight = w1110803)

select03
```


```{r join data frames (04), include=FALSE}

all04 <- p04 %>% 
  full_join(pequiv04, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "uhhnr", "hid"), stringsAsFactors = FALSE)
all04 <- all04 %>%
  full_join(pkind04, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "uhhnr", "hid", "welle"), stringsAsFactors = FALSE)
all04 <- all04 %>%
  full_join(pgen04, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "uhhnr", "hid"), stringsAsFactors = FALSE)

all04

```


```{r join data frames (04), echo=FALSE}

select04 <- all04 %>%
  select(persnr, pid, hhnr, cid, up7807, d11102ll, d1110804, e1110104, l1110204, d1110704, up14408, up13902, isced97_04, partz04, lfs04, uerwzeit, e1110104, i1111004, d1110104, w1110804) %>%
  rename(parleave = up7807, sex = d11102ll, education = d1110804, occup = e1110104,  region = l1110204, kinderzahl = d1110704, kindbd = up14408, birthyear = up13902, edisced = isced97_04, partner= partz04, employ = lfs04, workhpw = uerwzeit, workhpy = e1110104, income = i1111004, age = d1110104, longweight = w1110804)

select04
```

```{r join data frames (05), include=FALSE}

all05 <- p05 %>% 
  full_join(pequiv05, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "vhhnr", "hid"), stringsAsFactors = FALSE)
all05 <- all05 %>%
  full_join(pkind05, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "vhhnr", "hid", "welle"), stringsAsFactors = FALSE)
all05 <- all05 %>%
  full_join(pgen05, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "vhhnr", "hid"), stringsAsFactors = FALSE)

all05

```


```{r join data frames (05), echo=FALSE}

select05 <- all05 %>%
  select(persnr, pid, hhnr, cid, vp9908, d11102ll, d1110805, e1110105, l1110205, d1110705, vp15308, vp14702, isced97_05, partz05, lfs05, verwzeit, e1110105, i1111005, d1110105, w1110805) %>%
  rename(parleave = vp9908, sex = d11102ll, education = d1110805, occup = e1110105,  region = l1110205, kinderzahl = d1110705, kindbd = vp15308, birthyear = vp14702, edisced = isced97_05, partner= partz05, employ = lfs05, workhpw = verwzeit, workhpy = e1110105, income = i1111005, age = d1110105, longweight = w1110805)

select05
```


```{r join data frames (06), include=FALSE}

all06 <- p06 %>% 
  full_join(pequiv06, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "whhnr", "hid"), stringsAsFactors = FALSE)
all06 <- all06 %>%
  full_join(pkind06, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "whhnr", "hid", "welle"), stringsAsFactors = FALSE)
all06 <- all06 %>%
  full_join(pgen06, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "whhnr", "hid"), stringsAsFactors = FALSE)

all06

```


```{r join data frames (06), echo=FALSE}

select06 <- all06 %>%
  select(persnr, pid, hhnr, cid, wp7608, d11102ll, d1110806, e1110106, l1110206, d1110706, wp14108, wp12402, isced97_06, partz06, lfs06, werwzeit, e1110106, i1111006, d1110106, w1110806) %>%
  rename(parleave = wp7608, sex = d11102ll, education = d1110806, occup = e1110106,  region = l1110206, kinderzahl = d1110706, kindbd = wp14108, birthyear = wp12402, edisced = isced97_06, partner= partz06, employ = lfs06, workhpw = werwzeit, workhpy = e1110106, income = i1111006, age = d1110106, longweight = w1110806)

select06
```


```{r join data frames (07), include=FALSE}

all07 <- p07 %>% 
  full_join(pequiv07, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "xhhnr", "hid"), stringsAsFactors = FALSE)
all07 <- all07 %>%
  full_join(pkind07, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "xhhnr", "hid", "welle"), stringsAsFactors = FALSE)
all07 <- all07 %>%
  full_join(pgen07, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "xhhnr", "hid"), stringsAsFactors = FALSE)

all07

```


```{r join data frames (07), echo=FALSE}

select07 <- all07 %>%
  select(persnr, pid, hhnr, cid, xp9308, d11102ll, d1110807, e1110107, l1110207, d1110707, xp14808, xp13102, isced97_07, partz07, lfs07, xerwzeit, e1110107, i1111007, d1110107, w1110807) %>%
  rename(parleave = xp9308, sex = d11102ll, education = d1110807, occup = e1110107,  region = l1110207, kinderzahl = d1110707, kindbd = xp14808, birthyear = xp13102, edisced = isced97_07, partner= partz07, employ = lfs07, workhpw = xerwzeit, workhpy = e1110107, income = i1111007, age = d1110107, longweight = w1110807)

select07
```


```{r join data frames (08), include=FALSE}

all08 <- p08 %>% 
  full_join(pequiv08, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "yhhnr", "hid"), stringsAsFactors = FALSE)
all08 <- all08 %>%
  full_join(pkind08, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "yhhnr", "hid", "welle"), stringsAsFactors = FALSE)
all08 <- all08 %>%
  full_join(pgen08, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "yhhnr", "hid"), stringsAsFactors = FALSE)

all08

```


```{r join data frames (08), echo=FALSE}

select08 <- all08 %>%
  select(persnr, pid, hhnr, cid, yp9408, d11102ll, d1110808, e1110108, l1110208, d1110708, yp15408, yp14802, isced97_08, partz08, lfs08, yerwzeit, e1110108, i1111008, d1110108, w1110808) %>%
  rename(parleave = yp9408, sex = d11102ll, education = d1110808, occup = e1110108,  region = l1110208, kinderzahl = d1110708, kindbd = yp15408, birthyear = yp14802, edisced = isced97_08, partner= partz08, employ = lfs08, workhpw = yerwzeit, workhpy = e1110108, income = i1111008, age = d1110108, longweight = w1110808)

select08
```


```{r join data frames (09), include=FALSE}

all09 <- p09 %>% 
  full_join(pequiv09, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "zhhnr", "hid"), stringsAsFactors = FALSE)
all09 <- all09 %>%
  full_join(pkind09, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "zhhnr", "hid", "welle"), stringsAsFactors = FALSE)
all09 <- all09 %>%
  full_join(pgen09, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "zhhnr", "hid"), stringsAsFactors = FALSE)

all09

```


```{r join data frames (09), echo=FALSE}

select09 <- all09 %>%
  select(persnr, pid, hhnr, cid, zp9008, d11102ll, d1110809, e1110109, l1110209, d1110709, zp15608, zp12902 , isced97_09, partz09, lfs09, zerwzeit, e1110109, i1111009, d1110109, w1110809) %>%
  rename(parleave = zp9008, sex = d11102ll, education = d1110809, occup = e1110109,  region = l1110209, kinderzahl = d1110709, kindbd = zp15608, birthyear = zp12902 , edisced = isced97_09, partner= partz09, employ = lfs09, workhpw = zerwzeit, workhpy = e1110109, income = i1111009, age = d1110109, longweight = w1110809)

select09
```


```{r join data frames (10), include=FALSE}

all10 <- p10 %>% 
  full_join(pequiv10, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "bahhnr", "hid"), stringsAsFactors = FALSE)
all10 <- all10 %>%
  full_join(pkind10, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "bahhnr", "hid"), stringsAsFactors = FALSE)
all10 <- all10 %>%
  full_join(pgen10, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "bahhnr", "hid"), stringsAsFactors = FALSE)

all10

```


```{r join data frames (10), echo=FALSE}

select10 <- all10 %>%
  select(persnr, pid, hhnr, cid, bap8108, d11102ll, d1110810, e1110110, l1110210, d1110710, bap15909, bap15002, isced97_10, partz10, lfs10, baerwzeit, e1110110, i1111010, d1110110, w1110810) %>%
  rename(parleave = bap8108, sex = d11102ll, education = d1110810, occup = e1110110,  region = l1110210, kinderzahl = d1110710, kindbd = bap15909, birthyear = bap15002 , edisced = isced97_10, partner= partz10, employ = lfs10, workhpw = baerwzeit, workhpy = e1110110, income = i1111010, age = d1110110, longweight = w1110810)

select10
```

```{r join data frames (11), include=FALSE}

all11 <- p11 %>% 
  full_join(pequiv11, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "bbhhnr", "hid"), stringsAsFactors = FALSE)
all11 <- all11 %>%
  full_join(pkind11, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "bbhhnr", "hid"), stringsAsFactors = FALSE)
all11 <- all11 %>%
  full_join(pgen11, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "bbhhnr", "hid"), stringsAsFactors = FALSE)

all11

```


```{r join data frames (11), echo=FALSE}

select11 <- all11 %>%
  select(persnr, pid, hhnr, cid, bbp9109, d11102ll, d1110811, e1110111, l1110211, d1110711, bbp15112, bbp13202, isced97_11, partz11, lfs11, bberwzeit, e1110111, i1111011, d1110111, w1110811) %>%
  rename(parleave = bbp9109, sex = d11102ll, education = d1110811, occup = e1110111,  region = l1110211, kinderzahl = d1110711, kindbd = bbp15112, birthyear =bbp13202, edisced = isced97_11, partner= partz11, employ = lfs11, workhpw = bberwzeit, workhpy = e1110111, income = i1111011, age = d1110111, longweight = w1110811)

select11
```

```{r join data frames (12), include=FALSE}

all12 <- p12 %>% 
  full_join(pequiv12, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "bchhnr", "hid"), stringsAsFactors = FALSE)
all12 <- all12 %>%
  full_join(pkind12, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "bchhnr", "hid"), stringsAsFactors = FALSE)
all12 <- all12 %>%
  full_join(pgen12, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "bchhnr", "hid"), stringsAsFactors = FALSE)

all12

```


```{r join data frames (12), echo=FALSE}

select12 <- all12 %>%
  select(persnr, pid, hhnr, cid, bcp7907, d11102ll, d1110812, e1110112, l1110212, d1110712, bcp15012, bcp12803, isced97_12, partz12, lfs12, bcerwzeit, e1110112, i1111012, d1110112, w1110812) %>%
  rename(parleave = bcp7907, sex = d11102ll, education = d1110812, occup = e1110112,  region = l1110212, kinderzahl = d1110712, kindbd = bcp15012, birthyear = bcp12803, edisced = isced97_12, partner= partz12, employ = lfs12, workhpw = bcerwzeit, workhpy = e1110112, income = i1111012, age = d1110112, longweight = w1110812)

select12
```

```{r join data frames (13), include=FALSE}

all13 <- p13 %>% 
  full_join(pequiv13, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "bdhhnr", "hid"), stringsAsFactors = FALSE)
all13 <- all13 %>%
  full_join(pkind13, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "bdhhnr", "hid"), stringsAsFactors = FALSE)
all13 <- all13 %>%
  full_join(pgen13, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "bdhhnr", "hid"), stringsAsFactors = FALSE)

all13

```


```{r join data frames (13), echo=FALSE}

select13 <- all13 %>%
  select(persnr, pid, hhnr, cid, bdp9709, d11102ll, d1110813, e1110113, l1110213, d1110713, bdp15712, bdp13403, isced97_13, partz13, lfs13, bderwzeit, e1110113, i1111013, d1110113, w1110813) %>%
  rename(parleave = bdp9709, sex = d11102ll, education = d1110813, occup = e1110113,  region = l1110213, kinderzahl = d1110713, kindbd = bdp15712, birthyear = bdp13403, edisced = isced97_13, partner= partz13, employ = lfs13, workhpw = bderwzeit, workhpy = e1110113, income = i1111013, age = d1110113, longweight = w1110813)

select13
```


```{r join data frames (14), include=FALSE}

all14 <- p14 %>% 
  full_join(pequiv14, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "behhnr", "hid"), stringsAsFactors = FALSE)
all14 <- all14 %>%
  full_join(pkind14, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "behhnr", "hid"), stringsAsFactors = FALSE)
all14 <- all14 %>%
  full_join(pgen14, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "behhnr", "hid"), stringsAsFactors = FALSE)

all14

```


```{r join data frames (14), echo=FALSE}

select14 <- all14 %>%
  select(persnr, pid, hhnr, cid, bep8409, d11102ll, d1110814, e1110114, l1110214, d1110714, bep15012, bep12603, isced97_14, partz14, lfs14, beerwzeit, e1110114, i1111014, d1110114, w1110814) %>%
  rename(parleave = bep8409, sex = d11102ll, education = d1110814, occup = e1110114,  region = l1110214, kinderzahl =d1110714, kindbd = bep15012, birthyear = bep12603, edisced = isced97_14, partner= partz14, employ = lfs14, workhpw = beerwzeit, workhpy = e1110114, income = i1111014, age = d1110114, longweight = w1110814)

select14
```


```{r join data frames (15), include=FALSE}

all15 <- p15 %>% 
  full_join(pequiv15, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "bfhhnr", "hid"), stringsAsFactors = FALSE)
all15 <- all15 %>%
  full_join(pkind15, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "bfhhnr", "hid"), stringsAsFactors = FALSE)
all15 <- all15 %>%
  full_join(pgen15, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "bfhhnr", "hid"), stringsAsFactors = FALSE)

all15$birt

```


```{r join data frames (15), echo=FALSE}

select15 <- all15 %>%
  select(persnr, pid, hhnr, cid, bfp11808, d11102ll, d1110815, e1110115, l1110215, d1110715, bfp17312, bfpbirthy, isced97_15, partz15, lfs15, bferwzeit, e1110115, i1111015, d1110115, w1110815) %>%
  rename(parleave = bfp11808, sex = d11102ll, education = d1110815, occup = e1110115,  region = l1110215, kinderzahl = d1110715, kindbd = bfp17312, birthyear = bfpbirthy, edisced = isced97_15, partner= partz15, employ = lfs15, workhpw = bferwzeit, workhpy = e1110115, income = i1111015, age = d1110115, longweight = w1110815)

select15
```


```{r join data frames (16), include=FALSE}

all16 <- p16 %>% 
  full_join(pequiv16, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "bghhnr", "hid"), stringsAsFactors = FALSE)
all16 <- all16 %>%
  full_join(pkind16, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "bghhnr", "hid"), stringsAsFactors = FALSE)
all16 <- all16 %>%
  full_join(pgen16, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "bghhnr", "hid"), stringsAsFactors = FALSE)
all16 <- all16 %>%
  full_join(pp16, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "bghhnr", "hid", "bgp10408", "bgpbirthy", "bgp17012"), stringsAsFactors = FALSE)

all16

```


```{r join data frames (16), echo=FALSE}

select16 <- all16 %>%
  select(persnr, pid, hhnr, cid, bgp10408, d11102ll, d1110816, e1110116, l1110216, d1110716, bgp17012, bgpbirthy, isced97_16, partz16, lfs16, bgerwzeit, e1110116, i1111016, d1110116, w1110816, bgpbirthy) %>%
  rename(parleave = bgp10408, sex = d11102ll, education = d1110816, occup = e1110116,  region = l1110216, kinderzahl = d1110716, kindbd = bgp17012, birthyear = bgpbirthy, edisced = isced97_16, partner= partz16, employ = lfs16, workhpw = bgerwzeit, workhpy = e1110116, income = i1111016, age = d1110116, longweight = w1110816)

select16 #no welle variable
```

```{r join data frames (17), include=FALSE}

all17 <- p17 %>% 
  full_join(pequiv17, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "hid"), stringsAsFactors = FALSE)
all17 <- all17 %>%
  full_join(pkind17, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "hid"), stringsAsFactors = FALSE)
all17 <- all17 %>%
  full_join(pgen17, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "hid"), stringsAsFactors = FALSE)
all17 <- all17 %>%
  full_join(pp17, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "hid", "bhp_122_08", "bhpbirthy", "bhp_117_08"), stringsAsFactors = FALSE)

all17

```


```{r join data frames (17), echo=FALSE}

select17 <- all17 %>%
  select(persnr, pid, hhnr, cid, bhp_122_08, d11102ll, d1110817, e1110117, l1110217, d1110717, bhp_117_08, bhpbirthy,  isced97_17, partz17, lfs17, bherwzeit, e1110117, i1111017, d1110117, w1110817) %>%
  rename(parleave = bhp_122_08, sex = d11102ll, education = d1110817, occup = e1110117,  region = l1110217, kinderzahl = d1110717,  kindbd = bhp_117_08, birthyear = bhpbirthy, edisced = isced97_17, partner= partz17, employ = lfs17, workhpw = bherwzeit, workhpy = e1110117, income = i1111017, age = d1110117, longweight = w1110817)

select17 #no welle variable
select17$kindbd <- as.factor(select17$kindbd)
```


```{r join data frames (18), include=FALSE}

all18 <- p18 %>% 
  full_join(pequiv18, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "hid"), stringsAsFactors = FALSE)
all18 <- all18 %>%
  full_join(pkind18, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "hid"), stringsAsFactors = FALSE)
all18 <- all18 %>%
  full_join(pgen18, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "hid"), stringsAsFactors = FALSE)
all18 <- all18 %>%
  full_join(pp18, by = c("persnr", "hhnr", "hhnrakt", "cid", "pid", "syear", "hid", "bip_123_08", "bipbirthy", "bip_201_12"), stringsAsFactors = FALSE)
all18$bipbirthy

```


```{r join data frames (18), echo=FALSE}

select18 <- all18 %>%
  select(persnr, pid, hhnr, cid, bip_123_08, d11102ll, d1110818, e1110118, l1110218, d1110718, bip_201_12, bipbirthy, isced97_18, partz18, lfs18, bierwzeit, e1110118, i1111018, d1110118, w1110818) %>%
  rename(parleave = bip_123_08, sex = d11102ll, education = d1110818, occup = e1110118,  region = l1110218, kinderzahl = d1110718, kindbd = bip_201_12, birthyear = bipbirthy, edisced = isced97_18, partner= partz18, employ = lfs18, workhpw = bierwzeit, workhpy = e1110118, income = i1111018, age = d1110118, longweight = w1110818)


select18 #no welle variable
```








```{r join data frames together , echo=FALSE}

full <- rbind(select96, select97, select98, select99, select00, select01, select02, select03, select04, select05, select06, select07,select08, select09, select10, select11, select11, select12, select13, select14, select15, select16, select17, select18)
full 
```























